Subject: Connexion =?utf-8?q?d=C3=A9mo?= LabResult 
From: "demo-labresult@labresult.fr"
To: "jualmarcha@free.fr"
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="===============2479016047964055592=="

--===============2479016047964055592==
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

Bonjour,

Pour acc=C3=A9der au site de d=C3=A9monstration LabResult, vous pouvez utilis=
er les identifiants suivant:

 patient :
  identifiant  : patient
  mot de passe : password

 m=C3=A9decin :
   identifiant  : docteur
   mot de passe : password

 biologiste :
  identifiant  : biologiste
  mot de passe : password

LabResult

Tel. : 07 82 42 32 12

--===============2479016047964055592==
MIME-Version: 1.0
Content-Type: multipart/related;
 boundary="===============7935482808143204957=="

--===============7935482808143204957==
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<html>
  <head></head>
  <body>
    <p>Bonjour,</p>

<p>Pour acc=C3=A9der au site de d=C3=A9monstration LabResult, vous pouvez uti=
liser les identifiants suivant:</p>
<ul>
 <li> patient :
  <ul>
  <li> identifiant  : patient</li>
  <li> mot de passe : password</li>
  </ul>
 </li>
<br>
 <li> m=C3=A9decin :
  <ul>
  <li> identifiant  : docteur</li>
  <li> mot de passe : password</li>
  </ul>
 </li>
<br>
 <li> biologiste :
  <ul>
  <li> identifiant  : biologiste</li>
  <li> mot de passe : password</li>
  </ul>
 </li>
</ul>

LabResult<br>
Tel : 07 82 42 32 12
<br>
    <img src=3D"cid:20150403133638.7475.94859@dowst-SVP1121B4E" \>
  </body>
</html>

--===============7935482808143204957==
Content-Type: logo/png
Content-Transfer-Encoding: base64
Content-ID: <20150403133638.7475.94859@dowst-SVP1121B4E>
MIME-Version: 1.0
Content-Disposition: inline

iVBORw0KGgoAAAANSUhEUgAAAJIAAAAoCAYAAAAVKqOdAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAIA==
Y0hSTQAAeiUAAICDAAD5/wAAgOkAAHUwAADqYAAAOpgAABdvkl/FRgAAETVJREFUeNrsnHmUFdWdxw==
P1Wv3v56X6Ebupu9EURcMZEENYACLnEXNU40IS5R40oymbiccECNCYlj1EnMjDgYlIxBkahoXBBURA==
WV1YGtmU0N10N72+verOH/f2e9XN6w27BQ79O6fOq1dV99atut/6Ld/fr0oTQtBTeXxjFTe/tQvyfA==
0PPm7cUNTAG+BxwPDAAyAAcQAmqBXcAHwMvAlkM+ky+Tol1rmbrqaUIeP6DRL70jxmE8dyZwO3ADkA==
38lxg4HxwPeBh4GVwEPAP/qn78gR/TCddxawF7i3CxClkonAMmAVMKx/Co9NIHmVJvkvwPc1+/o2sA==
FbiqfxqPLSDlAh8D03p5/AuVZuuXYwBIfuANYHQf9f8AcGeXR2kauLz9s34UA+kZ4IQ+PscjnWs7DQ==
4jFyqyqS//vlqALSLOCib+h6HgMCKffELQiFKK7cjtYLnEW/fLNAygXmfIPXUwb8or0iwhT4PA6MgA==
m5DL2w+joxBINwJ53/A13YgkNZUmEhCOsfX84bw2dSj74g6wrP6ZP4qApAPXHoZrygJ+kNBGjWEemg==
UEyx30V9DPohdPQBaQow9DBd1zQ0IBhj5OAMbhojlaLVb9OOSiCdfhivawJxMRQLFpwxiICh9890Hw==
S2/l2vKVBjoFKFEAPbXTFppSEXGRjMQdumzZU82hqQ4sAaYFmuaiLlT+8JklX5yW6+uf5SMMSJqaYg==
TUtO9XHAfcCFgLOHs48WMyWedA1MAZYJbqP7SNI0EAIaIxCJg8sAjwGRGKcMThvSatLsR2vCQqChIQ==
EP1c0jcOpH9XgDkAfL6mKjgFwzH7kEN7XYO6EJeOyuHpM0vZF4yR5TG4+e3dLNpWC9nerh0ahwbNMQ==
CMU4pSSDy0szOT7HR4HPwEAwyO/+ld/p+BHgAjJA7HhlV+jsgBkOu2PBvwb1rHLdMutT9GwBLcBXwA==
28jSlfAxhIl7gF8CTwO3pdj/FHCJwsTjPQVSvpqQggORuLXky4aVeI0JhzxUU4BD56ej8/EaOkPS3Q==
AFxXnsuiirpugEiHxggZDo1nLhjJ+aUZqY7KVQsAO2pDhQs2Vi4JnDhj7gn/rBjjMGNjhdal73QjsA==
H7gOWXFwLMgoIB04qYP9p8oHs23lhdEckwGxULbL79RTKfx460pYMMD0GAMIxQ+tqE0DmiJ8qyDAxA==
orYk9PcGpzO+wM/6/UFId0uzlap9KEaarrHiwpGMy+ueD+R0Gfid4XMaswZNqs0qJqOxCqHpK3TLXA==
F3H5ApauC00ITZ0hAIwDypE82MvATcATxwCQIuo31MH+UKr9xoAXNsvWpsCpa9w5OpfZx+Xh7yDSMQ==
tFY1doixtKZB1OKSIZkpd88clsX6Lxshw93BKTRoiXL/GYPbgCgUt/jHzno+rg1Tb1k0heNcPTybcw==
B6Un8IemQzTsQVgY8RjVOSWPo7G4cP8OLN2gxZuO0DS0JIDPUSq+QKnxbcCbx4hm0rrYrrXVSC2xxA==
5pgp+PWK3fx6fSUvTR7C+UVpKXv6WnRMxCSQ5mbmqJyEQxJD1tsCXDwki3vXVhKKmpAKzFHZ/vKR2Q==
iU0NUZOzlm5j3c4GcGrSB6sNU+Y1EkBK6lwp/uABtk6Yee3W8rMWl21+k3HbVpJfu5uIy0/E5WkF0w==
ayoafR9ZwXDfMQSkjqSV04215ZFcDnA5wOmQEU+WF0JxLnp1O7/6pJqo9Fd6h8rTNWiMcGFJOgVeGQ==
5NWH4/zs3T3URkwAyjLcXDg4HZoi8viDgBhnXI6PIr8rsWne6r2sq6iDgQHI9UGOD/L9pPmcnYafug==
sKbhdM3ZOeq7vDhtNu+Pm4EzHsYXbsZK+k+bgN+o9YnAd7pxpSXA+cq3uh44Dyg6RH/lKuAa5ZvoRw==
EJDMrgnJdDemQ2fO8i+Y/Mp2miJmU+8MQYBT55oRSW2yprqFJ9/7ii0NycDoquHZyePbI8C0yPG1jQ==
EdbWhyHDk1Q8QoAQdPpeg6ahWRbEIvfQuL8cM8an4y/guXPupi6jEHe0jQvwkm39tE56vQJ4D/mywg==
S8BfVJSzFPgSWN5NIA5WftlmZOHeM8CHwIYOzv+YuvJf9mA2fqfaPNzFcZOA3cA6NYaxavtPkPXzFQ==
wDt6BxPuw9CnMzDtrnfXV97yh/WV5/WKxW2KclK+nymDk1HWK3saoSXK0h3JSHx6WSblhQFoiSXJRg==
m1aLxNtmzPwOxUMdGi3kRNNuIxqCYB3Ng8ay5oTzcJhRuyLeo+gAgNIUfRQrAC0CvqW27QfWAp8DUQ==
dQemACuA/+kkYi5FVpLOUP+bbY7tWGC1In7tMswGwO7KkHZt6WQ8rS9gnEqyTGcgcIZqf5J+0E2VZQ==
GF8By7DEb0hzP+p0O07++kDSIGJycVnSyW6OWyze1QB5PpbuakiGhsCVZZkQjLUFhwDcBhtqgtSFkw==
R08ry4TGMATjXfiJHcqFaFoBloBoCOEOSMc8qdEctokXKW70ahuAFqiJLgBOVqTtQGCm0igA/6Y0Tg==
KnmUZMXETSoUzwJ+bjvmgQ6i6lgPrjneLkrrSD4A/gDcr7ijPWr7W8AtyILCuXYgFQGfAnPVwG2RWg==
LzDAURNnmivhZAMs21FPVU0Qcn1sqQmyfGdDYt+lQ7MwAk6ImW37cRtU1YVZuLkmsWnW6DzunzxEmg==
qsYIHAhBTZCWcLy7oytAiG9juEB3kP/VJln8lrzucqBQrW9tR+g+r+6dCZyrQPJxO8DVKm01HvizLQ==
Inyk3ThOVv4UwGxFNwg12Q8BT6p95yp6oi+jM2zX+zMF3nnKzAG8qkzq3cA8w0Y4rupAbfeekz0yhw==
kkDSSX62ok4y1LoGpsWiHXVML5Nmb1S2lxnF6by4/QDk2JluAWku7li9F7/LwfXHyYf3vlMHcsOYPA==
1lYHqY2a1EfinDEgrXvjEwKc7nH4s/8+7qPFnL5xGY3+bPsRd9jWV9nW7yKZU5yporyuZJYC3jRknQ==
+f8CG23Odau8kaLtswpAuiKID4coZ5Q2N8iw0d6lfXZqS4CucfWIpDbaXBfm1b2NkO6SidaAi2V7Gg==
qQ7FyffKYf1gZA4vVtS1fbY1CTyzPsKCzTVcUZ6HX+nVAp+TaalZ7i6eSR0Md94JHy3m9PVLafJnYw==
6Y5WCuBR4AJ15AvAetsN/aFtghf34Iz3AFOVyZwF3JzCzKQqCFxlM6FHlOjAZJs67RtaqyVGeZ6PGQ==
NhJy4ef7MauCEBPSt7GgYV8zCz/bnzhmRlkmZfl+CEZlPxoQs6AhwhPnDefdS8oTIDpkEQLS8xldsQ==
atzkVQvOrE/Pnxg3nJM1IW4FPlF+QKvTay/jPQsYodaf7OFZP1NEJ8B021O+yea7zKWj+vMjUAzg8g==
vuVHNQjFuPzEwgTXYAEra4KkFadREHAiBGiaxh4NVlS3JOyIU9e4qjSTOau/goBLaqaGEHNOL+YGWw==
Zj8YM1mwpZZ3q1toiFqgQ21TlJvG5HOtzSejI3pVCEzD2NviS/+90PTjNXFQHeUB5CvjFbZt49Xvlw==
yreE7ucu48pZvV5xTscDa5Q/8jhwKzLXtU05ui8A2490IE3o0zPETPA7udLGHcVMwcvTh5Pu1NuUvg==
SobAJGbJdA3AxcMymbOhUmqiqElJnp9bxxck2lQFY3x3yTa27m0Et0MmdDVZXTCxOz6SpkMsTIM/dw==
UdzpcetWfJFK5jao0H0tssqhql3LooSjLj9s4eoBcWu1O3aYAhLIjLtfgWwA8KBaNiHfUP6TTWsdUQ==
pq2g73rXoDHKBUUZjMj0JAMvh0aGSg47bIsOZLgcCRABnJDnZ2pxOjRHIWIybVAaaU5HYv/dK/aw9Q==
ywYoTpeMdqYbMl2Q7SHg6aaCCDdRmT+scm/hyOe84abWFEgY+RrVLSlAZNc+TnUPs5QD2p0lF8ix8Q==
Q+3f2vyRIh7/qjgolNb6o/LR8jqIvHqSgdB6G0h9J0IAgiuHZ36tbq4emS3fSwNK05LBSk0oxvLqFg==
+Xkd01KMNoml23dVWJvQWB1x+dAE96geCrpgihttfk2mOr64B8tgYDjyFapUjvoaZHqkQEV3rXzHGA==
BbBUaQvtcAHJACqx1e30qgTjDM3x8f1hSbP2zt4mHlxXyYAMV8qZNoFgMM7s8YWcUuiXbGFZFgW5fg==
qvY1outJ7FcG49TErNTJ3Z75cQux4kIIEzRtnUobzAZ+CrzeAXm4Sf0OQn4QY18fPY71yHTGUypqGw==
i/yW1LmKy8Gm2XrinLt7G0gfKJT3LpR1DZqjXDomD5fNVD28Zh/LN1ZKM9RRvVFNiIBT5+nCMnl3nA==
OjNLM5i/tZZ9oaR7MMDvJM/QqTItMByHkFoWIMROLPFkO69lHjJvVqJA9QYHV0m+pyYwG5nO+HMPJw==
cZrqfw/wdwWCacrM/RP52Z/2GvAuZL4OxV+1AqkVxMU9GENRbwJJV8xst8UUEI1bELWkA5xqAWmKfA==
Tq60lXt8UhPk1epmKMuELDdkew5esjxQksHLe5vYb2OmLxuaCX6DlZXNiW05HoOLyjLgX00QMRMRGA==
QlNJW9GZOcN0usETuB2PrwmPH3S9FdwNSiO1koQ/T9HDF8Df1PqdKfyczuQqBZ75JL+JUKjm4mnFeg==
p5KNamwoc9oqFTZmPLsb5x/Xi8x4AkhvAi/2Km+kAY0RpgwMcHxOsvjsbzvqoSUqTZHNlzlocTuoqw==
D7Okoi7RdkJhgAkjcvhoax0f7g8mts8/YzA3TByMQwBNMVnH3RyFxijhqNlptOYJNszDjL/k0A3Q9A==
xCsBSp63AWU2Mk3SXuYpTTVSRVTdkfEKQAAfIWucUOH9BrU+qYO2BcgyV4DqdtoRte/qbozhP/oi/A==
R4Waxynnr1PJdTlYe8EIYkLgaJeDS3Pq1ERMznx9Jw2hOFfYfCNLwLPb68Dv6toECcCh8/yOA8wamw==
/KDbdeW5rN5Yxb0f/ovlM4YlIsAnJpXwwGlFfFIbImxaOICWmMXoHG8bhGvCAk3H0nRafNmUb1u5bQ==
xM41if2OeJigtw0zPltphzRkXmx6u5FuUX7UU8iaoQLkW75VHVzZZcB/q/A+jqxXst+N15SGulpprA==
Je3a32dbX25bX694qbPUODciqwxSyX8ii/f7BEh1yKKtN0jWm6RuoGuMsoXyBwHNKwiH47gyPVxmMw==
ay99cYAd1UHI9UJXH0AVMp/21r4WNtaGGKcAcVFpBr8Yksnrn+3n9nQX87+TrJrI9xqcXdwxbxQ3LQ==
okIDv/dDZzxaHHc4iwwrFvA0tyA0WeoWc3rsqRGAnUrrzFX+yyzF49jlL8gM/e+QZSK7VRT2tvJdDA==
xYBfQbL8w0SmXT5t19dvkUnfQpvpW4LMhd6m5ghl/tal0DKrFB3xjorsXkGWsxjKlF2nOKtq5XMN6w==
4nHubLvoKPyvUk/DHSqSOyRpMQWRlijXjMjG70h2/9z2OkkUdreSwNAhHGfhlto2PtEVQ7LBY/D7DQ==
lUxduo2Khki3unNrFp6MnJ+Ub3x9Qm7Nrvqw24epG76I20fU5SXq8iE03Q6iVnmIZH7tUeDEFN3PVw==
5mincqSvUZrnVRXx/dYGojVK+7+Sop8a4GKg1XbfDrwL/J8NRC8AP07R9gMF5FbeaSayKG458nOLcw==
FXBagLNtkWh7365VS3T0VLZu96fSSHY+Yr6i6Scqv8DbEyY1Ygl0p4OpNu1QHYzxWmULBJzdfwHfEg==
4HHw9r62xZnTS9L546YqSHfx+q4GRu7+hPEDA+LJSSWckuPNUc6m1u6JSRuQ4dv57IjaP81/YhlBbw==
xmMaolRpje6w0D9UGmkAHX88dYWaqMsUGI5TxKGlNNMGZCnJ8i7O977SYHcoUzVQAetTFRku7aTtmw==
KnL7MXCm4qrS1PztU/sfURZopZr/9jXozwNNahyp5EGVvrFXjfL/AwBkd5grqfbg4QAAAABJRU5Erg==
QmCC

--===============7935482808143204957==--

--===============2479016047964055592==--
