#!/bin/bash

docker stop db
docker stop rabbitmq
docker rm db
docker rm rabbitmq
docker run -v /data/db:/data/db --name db -d -p 27017:27017 mongo
docker run -d --name rabbitmq -p 5672:5672 rabbitmq
docker run -d --link db:db --link rabbitmq:rabbitmq --name celery dowst/labresult:0.1 /labresult/bin/python /labresult/runcelery.py conf=prod worker -l INFO
docker run -d --name labresult-demo --link db:db --link rabbitmq:rabbitmq dowst/labresult:0.1 
sudo docker run -d --name labresult-nginx --link labresult-demo:labresult-demo -p 80:80 -p 443:443 dowst/labresult-nginx
