#!/bin/bash
/usr/bin/pyvenv-3.4 --without-pip $1
source ./$1/bin/activate
wget https://pypi.python.org/packages/source/s/setuptools/setuptools-3.4.4.tar.gz
tar -vzxf setuptools-3.4.4.tar.gz
cd setuptools-3.4.4
python3.4 setup.py install
cd ..
wget https://pypi.python.org/packages/source/p/pip/pip-1.5.6.tar.gz
tar -vzxf pip-1.5.6.tar.gz
cd pip-1.5.6
python3.4 setup.py install
cd ..
deactivate
source ./$1/bin/activate

